// Auto-generated by scripts/fetch-mentorship-images.mjs
// Sources: Wikipedia/Wikimedia public pages and images

export type MentorshipStoryImageMeta = {
  imageUrl: string;
  sourceUrl: string;
  sourceTitle: string;
};

export const mentorshipStoryImageById: Partial<Record<string, MentorshipStoryImageMeta>> = {
  "ada-lovelace": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Ada_Lovelace_daguerreotype_by_Antoine_Claudet_1843_-_cropped.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Ada_Lovelace",
    sourceTitle: "Ada Lovelace",
  },
  "adenike-oladosu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/AdenikeOladosu2020-ElevateFestival.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Adenike_Oladosu",
    sourceTitle: "Adenike Oladosu",
  },
  "agnes-kalibata": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Agnes_Kalibata_-_2019_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Agnes_Kalibata",
    sourceTitle: "Agnes Kalibata",
  },
  "akinwumi-adesina": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Akinwumi_Adesina_-_2014_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Akinwumi_Adesina",
    sourceTitle: "Akinwumi Adesina",
  },
  "alice-walker": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Alice_Walker.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Alice_Walker",
    sourceTitle: "Alice Walker",
  },
  "ama-ata-aidoo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/aa/Ama_Ata_Aidoo.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Ama_Ata_Aidoo",
    sourceTitle: "Ama Ata Aidoo",
  },
  "amina-j-mohammed": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/UN_Deputy_Secretary_General_Amina_J._Mohammed_%283x4_cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Amina_J._Mohammed",
    sourceTitle: "Amina J. Mohammed",
  },
  "beko-ransome-kuti": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Beko_Ransome_Kuti_Park_17.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Beko_Ransome-Kuti",
    sourceTitle: "Beko Ransome-Kuti",
  },
  "ben-enwonwu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/ac/Ben_Enwonwu.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Ben_Enwonwu",
    sourceTitle: "Ben Enwonwu",
  },
  "bethlehem-alemu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/SoleRebels_Bethlehem_Tilahun_Alemu.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Bethlehem_Tilahun_Alemu",
    sourceTitle: "Bethlehem Tilahun Alemu",
  },
  "bolanle-olukanni": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Bolanle_Olukanni_2019_ndantv.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Bolanle_Olukanni",
    sourceTitle: "Bolanle Olukanni",
  },
  "cheikh-anta-diop": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/83/Cheikh_Anta_Diop%2C_late_1940s.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Cheikh_Anta_Diop",
    sourceTitle: "Cheikh Anta Diop",
  },
  "chimamanda-adichie": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Chimamanda_Ngozi_Adichie_%282015%29.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Chimamanda_Ngozi_Adichie",
    sourceTitle: "Chimamanda Ngozi Adichie",
  },
  "chinua-achebe": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Chinua_Achebe%2C_1966.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Chinua_Achebe",
    sourceTitle: "Chinua Achebe",
  },
  "desmond-tutu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Archbishop-Tutu-medium.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Desmond_Tutu",
    sourceTitle: "Desmond Tutu",
  },
  "dora-akunyili": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/ce/Photo_of_Dora_Akunyili.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Dora_Akunyili",
    sourceTitle: "Dora Akunyili",
  },
  "ellen-johnson-sirleaf": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ellen_Johnson_Sirleaf_February_2015.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ellen_Johnson_Sirleaf",
    sourceTitle: "Ellen Johnson Sirleaf",
  },
  "fatima-al-fihri": {
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Fatima%20Fihria%20(cropped).jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Fatima_al-Fihriya",
    sourceTitle: "Fatima al-Fihriya",
  },
  "fela-kuti": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Fela_Kuti_circa_1986.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Fela_Kuti",
    sourceTitle: "Fela Kuti",
  },
  "francisca-okeke": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Prof._Francisca_Okeke.jpg/3000px-Prof._Francisca_Okeke.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Francisca_Nneka_Okeke",
    sourceTitle: "Francisca Nneka Okeke",
  },
  "funmilayo-ransome-kuti": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/70_year_old_Funmilayo_Ransome-Kuti_on_her_birthday.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Funmilayo_Ransome-Kuti",
    sourceTitle: "Funmilayo Ransome-Kuti",
  },
  "gambo-sawaba": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f7/Photo_of_Hajia_Sawaba_Gambo.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Gambo_Sawaba",
    sourceTitle: "Gambo Sawaba",
  },
  "genevieve-nnaji": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Genevieve_Nnaji_in_Weekend_Getaway.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Genevieve_Nnaji",
    sourceTitle: "Genevieve Nnaji",
  },
  "george-washington-carver": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/George_Washington_Carver_c1910_-_Restoration.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/George_Washington_Carver",
    sourceTitle: "George Washington Carver",
  },
  "gladys-west": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/181206-F-DT527-087_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Gladys_West",
    sourceTitle: "Gladys West",
  },
  "graca-machel": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Madame_Graca_Machel.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Gra%C3%A7a_Machel",
    sourceTitle: "Graça Machel",
  },
  "grace-alele-williams": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/7d/Grace_Alele-Williams.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Grace_Alele-Williams",
    sourceTitle: "Grace Alele-Williams",
  },
  "granville-woods": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Woodsgr.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Granville_Woods",
    sourceTitle: "Granville Woods",
  },
  "hafsat-abiola": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Hafsat_Abiola_Nigerian_activist.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Hafsat_Abiola",
    sourceTitle: "Hafsat Abiola",
  },
  "hedy-lamarr": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/83/Hedy_Lamarr_Publicity_Photo_for_The_Heavenly_Body_1944.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Hedy_Lamarr",
    sourceTitle: "Hedy Lamarr",
  },
  "herbert-macaulay": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Herbert_Macaulay_portrait.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Herbert_Macaulay",
    sourceTitle: "Herbert Macaulay",
  },
  "iyinoluwa-aboyeji": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/YGL_Alumni_Annual_Summit_2018_%2844711810794%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Iyinoluwa_Aboyeji",
    sourceTitle: "Iyinoluwa Aboyeji",
  },
  "james-west": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/James_West_%28professor%29_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/James_West_(inventor)",
    sourceTitle: "James West (inventor)",
  },
  "jelani-aliyu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Aliyu-jelani.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Jelani_Aliyu",
    sourceTitle: "Jelani Aliyu",
  },
  "joke-silva": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Joke_Silva.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Joke_Silva",
    sourceTitle: "Joke Silva",
  },
  "juliana-rotich": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Juliana_Rotich_in_Berlin%2C_April_2017_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Juliana_Rotich",
    sourceTitle: "Juliana Rotich",
  },
  "julius-nyerere": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/President_Nyerere_1975.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Julius_Nyerere",
    sourceTitle: "Julius Nyerere",
  },
  "katherine-johnson": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Katherine_Johnson_1983.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Katherine_Johnson",
    sourceTitle: "Katherine Johnson",
  },
  "ken-saro-wiwa": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/2a/Ken_Saro-Wiwa.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ken_Saro-Wiwa",
    sourceTitle: "Ken Saro-Wiwa",
  },
  "kofi-annan": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Kofi_Annan_2012_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Kofi_Annan",
    sourceTitle: "Kofi Annan",
  },
  "kudirat-abiola": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/40/Kudirat_Abiola_fair_use.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Kudirat_Abiola",
    sourceTitle: "Kudirat Abiola",
  },
  "kunle-olukotun": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/KunleOlukotun-2018photo.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Kunle_Olukotun",
    sourceTitle: "Kunle Olukotun",
  },
  "kwame-nkrumah": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Kwame_Nkrumah_Portrait%2C_The_National_Archives_UK.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Kwame_Nkrumah",
    sourceTitle: "Kwame Nkrumah",
  },
  "ladi-kwali": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/5/59/Photo_of_Ladi_Kwali.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ladi_Kwali",
    sourceTitle: "Ladi Kwali",
  },
  "lewis-latimer": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Lewis_latimer.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Lewis_Howard_Latimer",
    sourceTitle: "Lewis Howard Latimer",
  },
  "leymah-gbowee": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Leymah_Gbowee_no_Fronteiras_do_Pensamento_Porto_Alegre_2013_%289730602149%29_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Leymah_Gbowee",
    sourceTitle: "Leymah Gbowee",
  },
  "lupita-nyongo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Lupita_Nyong%27o_by_Gage_Skidmore_4.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Lupita_Nyong'o",
    sourceTitle: "Lupita Nyong'o",
  },
  "mae-jemison": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/Mae_Carol_Jemison.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mae_Jemison",
    sourceTitle: "Mae Jemison",
  },
  "margaret-ekpo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/27/Mrs_Margaret_Affiong_Ekpo.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Margaret_Ekpo",
    sourceTitle: "Margaret Ekpo",
  },
  "marie-curie": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Marie_Curie_c._1920s.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Marie_Curie",
    sourceTitle: "Marie Curie",
  },
  "mark-dean": {
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Mark%20Dean%20football%20coach%20-%201953.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mark_Dean_(American_football)",
    sourceTitle: "Mark Dean",
  },
  "maya-angelou": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Angelou_at_Clinton_inauguration_%28cropped_2%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Maya_Angelou",
    sourceTitle: "Maya Angelou",
  },
  "miriam-makeba": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Miriam_makeba_01.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Miriam_Makeba",
    sourceTitle: "Miriam Makeba",
  },
  "mo-abudu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Mosunmola_Abudu_1.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mo_Abudu",
    sourceTitle: "Mo Abudu",
  },
  "mo-ibrahim": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Mo_Ibrahim.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mo_Ibrahim",
    sourceTitle: "Mo Ibrahim",
  },
  "nadine-gordimer": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/37/Nadine_Gordimer_01.JPG",
    sourceUrl: "https://en.wikipedia.org/wiki/Nadine_Gordimer",
    sourceTitle: "Nadine Gordimer",
  },
  "nawal-el-saadawi": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Nawal_el_Saadawi_01.JPG",
    sourceUrl: "https://en.wikipedia.org/wiki/Nawal_El_Saadawi",
    sourceTitle: "Nawal El Saadawi",
  },
  "ndidi-nwuneli": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Ndidi_Nwuneli--0.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ndidi_Okonkwo_Nwuneli",
    sourceTitle: "Ndidi Okonkwo Nwuneli",
  },
  "nelson-mandela": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nelson_Mandela",
    sourceTitle: "Nelson Mandela",
  },
  "ngozi-okonjo-iweala": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Ngozi_Okonjo-Iweala_takes_over_as_new_WTO_Director-General%2C_1_March_2021_%2850993534756%29_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ngozi_Okonjo-Iweala",
    sourceTitle: "Ngozi Okonjo-Iweala",
  },
  "nike-davies-okundaye": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Chief_Nike_Davies_Okundaye.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nike_Davies-Okundaye",
    sourceTitle: "Nike Davies-Okundaye",
  },
  "nina-simone": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Nina_Simone_-1969.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nina_Simone",
    sourceTitle: "Nina Simone",
  },
  "nnamdi-azikiwe": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Nnamdi_Azikiwe_PC_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nnamdi_Azikiwe",
    sourceTitle: "Nnamdi Azikiwe",
  },
  "nnedi-okorafor": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Nnedi_Okorafor_2023.jpeg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nnedi_Okorafor",
    sourceTitle: "Nnedi Okorafor",
  },
  "obafemi-awolowo": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Obafemi_Awolowo.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Obafemi_Awolowo",
    sourceTitle: "Obafemi Awolowo",
  },
  "oby-ezekwesili": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Obiageli_Katryn_Ezekwesili%2C_2009_World_Economic_Forum_on_Africa.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Oby_Ezekwesili",
    sourceTitle: "Oby Ezekwesili",
  },
  "ola-orekunrin": {
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ola%20Orekunrin%202.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Ola_Brown",
    sourceTitle: "Ola Brown",
  },
  "olikoye-ransome-kuti": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/5/5a/Olikoye_Ransome-Kuti.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Olikoye_Ransome-Kuti",
    sourceTitle: "Olikoye Ransome-Kuti",
  },
  "olufunmilayo-olopade": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Funmi_Olopade_-_Integrating_Women%27s_Health_into_the_Global_Health_Agenda_%2811_30_am%29_2-20_screenshot.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Olufunmilayo_Olopade",
    sourceTitle: "Olufunmilayo Olopade",
  },
  "onyeka-onwenu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Onyeka_Onwenu_in_June_2022_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Onyeka_Onwenu",
    sourceTitle: "Onyeka Onwenu",
  },
  "patrice-lumumba": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Patrice_Lumumba%2C_1960_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Patrice_Lumumba",
    sourceTitle: "Patrice Lumumba",
  },
  "patricia-bath": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Patriciabath.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Patricia_Bath",
    sourceTitle: "Patricia Bath",
  },
  "philip-emeagwali": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Philip_Emeagwali_with_scribbled_Exxon-Mobil_equations.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Philip_Emeagwali",
    sourceTitle: "Philip Emeagwali",
  },
  "quarraisha-abdool-karim": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Quarraisha_Abdool_Karim.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Quarraisha_Abdool_Karim",
    sourceTitle: "Quarraisha Abdool Karim",
  },
  "queen-amina-zazzau": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Queen_Amina_Statue_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Amina_of_Zazzau",
    sourceTitle: "Amina of Zazzau",
  },
  "queen-nzinga": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Ann_Zingha.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Nzinga_of_Ndongo_and_Matamba",
    sourceTitle: "Nzinga of Ndongo and Matamba",
  },
  "rosalind-franklin": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Rosalind_Franklin_%28retouched%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Rosalind_Franklin",
    sourceTitle: "Rosalind Franklin",
  },
  "sameera-moussa": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/SameeraMoussa.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Sameera_Moussa",
    sourceTitle: "Sameera Moussa",
  },
  "samuel-ajayi-crowther": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Bishop_Samuel_Ajayi_Crowther_1867.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Samuel_Ajayi_Crowther",
    sourceTitle: "Samuel Ajayi Crowther",
  },
  "shirley-ann-jackson": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Shirley_Ann_Jackson_World_Economic_Forum_2010.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Shirley_Ann_Jackson",
    sourceTitle: "Shirley Ann Jackson",
  },
  "stella-adadevoh": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Ameyo_Adadevoh_way_Abuja.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Ameyo_Adadevoh",
    sourceTitle: "Ameyo Adadevoh",
  },
  "strive-masiyiwa": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Strive_Masiyawa%2C_Africa_Leadership_Academy%2C_Nairobi%2C_Kenya%2C_2019_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Strive_Masiyiwa",
    sourceTitle: "Strive Masiyiwa",
  },
  "tara-fela-durotoye": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Tara_Fela-Durotoye.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Tara_Fela-Durotoye",
    sourceTitle: "Tara Fela-Durotoye",
  },
  "thomas-sankara": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Thomas_Sankara_in_Harlem_%281984%29.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Thomas_Sankara",
    sourceTitle: "Thomas Sankara",
  },
  "toni-morrison": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Toni_Morrison.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Toni_Morrison",
    sourceTitle: "Toni Morrison",
  },
  "tony-elumelu": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Tony_Elumelu_-_2020_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Tony_Elumelu",
    sourceTitle: "Tony Elumelu",
  },
  "tu-youyou": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/D810_4987_Tu_Youyou%2C_medicine_%2822945001843%29_%28cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Tu_Youyou",
    sourceTitle: "Tu Youyou",
  },
  "valerie-thomas": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Valerie_L._Thomas_standing_with_a_stack_of_early_Landsat_Computer_Compatible_Tapes.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Valerie_Thomas",
    sourceTitle: "Valerie Thomas",
  },
  "wangari-maathai": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Wangari_Maathai_in_2001.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Wangar%C4%A9_Maathai",
    sourceTitle: "Wangarĩ Maathai",
  },
  "wanjira-mathai": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Wanjira_Mathai_at_Global_Scholars_Symposium_2013.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Wanjira_Mathai",
    sourceTitle: "Wanjira Mathai",
  },
  "wole-soyinka": {
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/78/Wole_Soyinka_in_2018_%283x4_cropped%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Wole_Soyinka",
    sourceTitle: "Wole Soyinka",
  },
  "yaa-asantewaa": {
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ejisu%20Roundabout.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Yaa_Asantewaa",
    sourceTitle: "Yaa Asantewaa",
  },
};
